support enterprise_project_id in  CSS, DWS,DIS
huaweicloud/terraform-provider-huaweicloud pull request #1313
Opened 2021-07-26 11:31 UTC by hmbig2

**What this PR does / why we need it**:
support enterprise_project_id in  CSS, DWS,DIS

**Which issue this PR fixes**:
fixes #1307 #1185

**Special notes for your reviewer**:

**Release note**:

```release-note

```

## PR Checklist

* [X] Tests added/passed.
* [X] Documentation updated.
* [X] Schema updated.

## Acceptance Steps Performed

```
make testacc TEST='./huaweicloud' TESTARGS='-run=TestAccDisStreamV2_basic'
...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./huaweicloud -v -run=TestAccDisStreamV2_basic -timeout 360m -parallel 4
=== RUN   TestAccDisStreamV2_basic
=== PAUSE TestAccDisStreamV2_basic
=== CONT  TestAccDisStreamV2_basic
--- PASS: TestAccDisStreamV2_basic (9.91s)
PASS
ok      github.com/huaweicloud/terraform-provider-huaweicloud/huaweicloud       9.957s
```
```
make testacc TEST='./huaweicloud' TESTARGS='-run=TestAccDwsCluster_basic'
...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./huaweicloud -v -run=TestAccDwsCluster_basic -timeout 360m -parallel 4
=== RUN   TestAccDwsCluster_basic
=== PAUSE TestAccDwsCluster_basic
=== CONT  TestAccDwsCluster_basic
--- PASS: TestAccDwsCluster_basic (1095.94s)
PASS
ok      github.com/huaweicloud/terraform-provider-huaweicloud/huaweicloud       1096.163s
```
```
make testacc TEST='./huaweicloud' TESTARGS='-run=TestAccCssClusterV1_basic'
...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./huaweicloud -v -run=TestAccCssClusterV1_basic -timeout 360m -parallel 4
=== RUN   TestAccCssClusterV1_basic
=== PAUSE TestAccCssClusterV1_basic
=== CONT  TestAccCssClusterV1_basic
--- PASS: TestAccCssClusterV1_basic (962.42s)
PASS
ok      github.com/huaweicloud/terraform-provider-huaweicloud/huaweicloud       962.711s
```

2021-07-30 07:14 UTC, chengxiangdong commented on huaweicloud/resource_huaweicloud_dis_stream_v2.go
> +		"auto_scale_enabled":             d.Get("auto_scale_enabled"),
`auto_scale_enabled` TBD

2021-07-30 09:36 UTC, ShiChangkuo requested changes

2021-07-30 09:36 UTC, ShiChangkuo commented on docs/resources/dws_cluster.md
> +  node_type             = "dws.m3.xlarge"
please keep the example usage as is.

2021-07-31 01:41 UTC, hmbig2 commented on docs/resources/dws_cluster.md
> +  node_type             = "dws.m3.xlarge"
revert

2021-07-31 03:43 UTC, ShiChangkuo approved these changes

2021-07-31 03:43 UTC, merged