refactor(DIS):refactor resource_huaweicloud_dis_stream_v2 to new SDK
huaweicloud/terraform-provider-huaweicloud pull request #1598
Opened 2021-10-13 02:27 UTC by hmbig2

**What this PR does / why we need it**:
refactor resource_huaweicloud_dis_stream_v2 to new SDK

**Which issue this PR fixes**:
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
fixes #1504 

**Special notes for your reviewer**:

**Release note**:

```release-note

```

## PR Checklist

* [X] Tests added/passed.
* [X] Documentation updated.
* [X] Schema updated.

## Acceptance Steps Performed

```
make testacc TEST='./huaweicloud/services/acceptance/dis' TESTARGS='-run=TestAccResourceDisStream'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./huaweicloud/services/acceptance/dis -v -run=TestAccResourceDisStream -timeout 360m -parallel 4
=== RUN   TestAccResourceDisStream_basic
=== PAUSE TestAccResourceDisStream_basic
=== RUN   TestAccResourceDisStream_all
=== PAUSE TestAccResourceDisStream_all
=== CONT  TestAccResourceDisStream_basic
=== CONT  TestAccResourceDisStream_all
--- PASS: TestAccResourceDisStream_all (42.54s)
--- PASS: TestAccResourceDisStream_basic (47.00s)
PASS
ok      github.com/huaweicloud/terraform-provider-huaweicloud/huaweicloud/services/acceptance/dis       47.076s
```

2021-10-16 10:14 UTC, Lance52259 commented on docs/resources/dis_stream.md
> +  Value range: `24` to `72`.Unit: `hour`. Default:`24`.
s/`72`.Unit/`72`. Unit

2021-10-16 10:14 UTC, Lance52259 commented on docs/resources/dis_stream.md
> +* `stream_id` - Specifies a stream ID in UUID format
missing period (.)

2021-10-16 10:14 UTC, Lance52259 commented on docs/resources/dis_stream.md
> +Dis stream can be imported by  `stream_name`. For example,
only one blank space between `by` and `stream_name`.

2021-10-16 10:14 UTC, Lance52259 commented on huaweicloud/services/dis/resource_huaweicloud_dis_stream.go
> +const DIS_SYS_TAG_KEY_ENTERPRISE_PROJECT_ID = "_sys_enterprise_project_id"
The value can be declared in common as a common constant for reference and the format of constant should be in `UpperCamelCase`.

2021-10-16 10:14 UTC, Lance52259 commented on huaweicloud/services/dis/resource_huaweicloud_dis_stream.go
> +				},
use validation.IntBetween(24, 72)

2021-10-24 04:00 UTC, ShiChangkuo requested changes

2021-10-24 04:00 UTC, ShiChangkuo commented on huaweicloud/utils/type_convert.go
> +}
I think this function is rare used, and we should support more type if necessary.
So, I think you can update it in another PR.

2021-10-24 04:00 UTC, ShiChangkuo commented on huaweicloud/config/config.go
> +func (c *Config) DisV3Client(region string) (*golangsdk.ServiceClient, error) {
the testing for this client is missing

2021-10-24 04:00 UTC, ShiChangkuo commented on huaweicloud/services/dis/resource_huaweicloud_dis_stream.go
> +			},
suggest to add **RequiredWith** attribute

2021-10-26 02:07 UTC, hmbig2 commented on huaweicloud/config/config.go
> +func (c *Config) DisV3Client(region string) (*golangsdk.ServiceClient, error) {
```
    endpoints_test.go:817: MRS v1.1 endpoint:    https://mrs.cn-north-4.myhuaweicloud.com/v1.1/0970dd7a1300f5672ff2c003c60ae115/
    endpoints_test.go:829: MRS v2 endpoint:      https://mrs.cn-north-4.myhuaweicloud.com/v2/0970dd7a1300f5672ff2c003c60ae115/
    endpoints_test.go:841: SMN endpoint:         https://smn.cn-north-4.myhuaweicloud.com/v2/0970dd7a1300f5672ff2c003c60ae115/notifications/
    endpoints_test.go:852: cdm endpoint:         https://cdm.cn-north-4.myhuaweicloud.com/v1.1/0970dd7a1300f5672ff2c003c60ae115/
    endpoints_test.go:863: dis endpoint:         https://dis.cn-north-4.myhuaweicloud.com/v2/0970dd7a1300f5672ff2c003c60ae115/
    endpoints_test.go:874: dis v3 endpoint:      https://dis.cn-north-4.myhuaweicloud.com/v3/0970dd7a1300f5672ff2c003c60ae115/
    endpoints_test.go:885: cloudtable endpoint:  https://cloudtable.cn-north-4.myhuaweicloud.com/v2/0970dd7a1300f5672ff2c003c60ae115/
    endpoints_test.go:896: cloudStream endpoint:         https://cs.cn-north-4.myhuaweicloud.com/v1.0/0970dd7a1300f5672ff2c003c60ae115/
    endpoints_test.go:907: css endpoint:         https://css.cn-north-4.myhuaweicloud.com/v1.0/0970dd7a1300f5672ff2c003c60ae115/
    endpoints_test.go:918: dli endpoint:         https://dli.cn-north-4.myhuaweicloud.com/v1.0/0970dd7a1300f5672ff2c003c60ae115/
    endpoints_test.go:929: dws endpoint:         https://dws.cn-north-4.myhuaweicloud.com/v1.0/0970dd7a1300f5672ff2c003c60ae115/
    endpoints_test.go:940: dws V2 endpoint:      https://dws.cn-north-4.myhuaweicloud.com/v2/0970dd7a1300f5672ff2c003c60ae115/
    endpoints_test.go:951: ges endpoint:         https://ges.cn-north-4.myhuaweicloud.com/v1.0/0970dd7a1300f5672ff2c003c60ae115/
    endpoints_test.go:962: mls endpoint:         https://mls.cn-north-4.myhuaweicloud.com/v1.0/0970dd7a1300f5672ff2c003c60ae115/
--- PASS: TestAccServiceEndpoints_EnterpriseIntelligence (1.34s)
PASS
ok      github.com/huaweicloud/terraform-provider-huaweicloud/huaweicloud       1.457s
```

2021-10-26 07:54 UTC, ShiChangkuo commented on docs/resources/dis_stream.md
> +* `retention_period` - (Optional, Int) The number of hours for which data from the stream will be retained in DIS.
this parameter is **ForceNew** in schema

2021-10-26 09:11 UTC, ShiChangkuo commented
/lgtm

2021-10-26 09:12 UTC, merged