feat(DLI): add new resource: dli table
huaweicloud/terraform-provider-huaweicloud pull request #1621
Opened 2021-10-22 03:13 UTC by hmbig2

**What this PR does / why we need it**:
add new resource: dli table

**Which issue this PR fixes**:
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
fixes #1602

**Special notes for your reviewer**:

**Release note**:

```release-note

```

## PR Checklist

* [X] Tests added/passed.
* [X] Documentation updated.
* [X] Schema updated.

## Acceptance Steps Performed
```
make testacc TEST='./huaweicloud/services/acceptance/dli' TESTARGS='-run=TestAccResourceDliTable_basic'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./huaweicloud/services/acceptance/dli -v -run=TestAccResourceDliTable_basic -timeout 360m -parallel 4
=== RUN   TestAccResourceDliTable_basic
=== PAUSE TestAccResourceDliTable_basic
=== CONT  TestAccResourceDliTable_basic
--- PASS: TestAccResourceDliTable_basic (23.45s)
PASS
ok      github.com/huaweicloud/terraform-provider-huaweicloud/huaweicloud/services/acceptance/dli       23.570s
```
```
make testacc TEST='./huaweicloud/services/acceptance/dli' TESTARGS='-run=TestAccResourceDliTable_OBS'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./huaweicloud/services/acceptance/dli -v -run=TestAccResourceDliTable_OBS -timeout 360m -parallel 4
=== RUN   TestAccResourceDliTable_OBS
=== PAUSE TestAccResourceDliTable_OBS
=== CONT  TestAccResourceDliTable_OBS
--- PASS: TestAccResourceDliTable_OBS (23.53s)
PASS
ok      github.com/huaweicloud/terraform-provider-huaweicloud/huaweicloud/services/acceptance/dli    
```

2021-10-22 08:35 UTC, Lance52259 commented on docs/resources/dli_table.md
> +  description        = "SQL table_1 description"
extra blank spaces.

2021-10-22 08:35 UTC, Lance52259 commented on docs/resources/dli_table.md
> +  a newresource. The options are as follows:
suggest to unify the description of ForceNew.

2021-10-22 08:35 UTC, Lance52259 commented on docs/resources/dli_table.md
> +* `name` - (Required, String, ForceNew) Name of a table. Name of a newly created resource table. The name can contain
maybe `Specifies the table name`?

2021-10-22 08:35 UTC, Lance52259 commented on docs/resources/dli_table.md
> +* `id` - a resource ID in format of **database.table**
suggest use slash to separate database and table.

2021-10-22 08:35 UTC, Lance52259 commented on docs/resources/dli_table.md
> +* `id` - a resource ID in format of **database.table**
A resource ID...

2021-10-22 08:35 UTC, Lance52259 commented on docs/resources/dli_table.md
> +DLI table can be imported by  `id`. For example,
One blank space between by and ID

2021-10-22 08:35 UTC, Lance52259 commented on docs/resources/dli_table.md
> +terraform import huaweicloud_dli_table.example  database.table
ditto

2021-10-22 08:35 UTC, Lance52259 commented on huaweicloud/services/acceptance/dli/resource_huaweicloud_dli_table_test.go
> +  description           = "For terraform acc test"
ditto

2021-10-22 08:35 UTC, Lance52259 commented on huaweicloud/services/dli/resource_huaweicloud_dli_table.go
> +func resourceDliTableRead(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
Use `_ context.Context` because ctx is never used.

2021-10-22 08:35 UTC, Lance52259 commented on huaweicloud/services/acceptance/dli/resource_huaweicloud_dli_table_test.go
> +	tableName := idArrays[1]
maybe use `ParseTableInfoFromId` is better.

2021-10-22 08:35 UTC, Lance52259 commented on huaweicloud/services/dli/resource_huaweicloud_dli_table.go
> +		WithDetail: Bool(true),
golangsdk.Enabled

2021-10-28 07:57 UTC, hmbig2 commented on docs/resources/dli_table.md
> +* `id` - a resource ID in format of **database.table**
> suggest use slash to separate database and table.
This format is more closer to the sql specification

> A resource ID...

OK

2021-10-28 08:16 UTC, hmbig2 commented on huaweicloud/services/dli/resource_huaweicloud_dli_table.go
> +		WithDetail: Bool(true),
OK, convert bool to *bool  by utils.Bool()

2021-10-28 08:46 UTC, ShiChangkuo requested changes

2021-10-28 08:46 UTC, ShiChangkuo commented on docs/resources/dli_table.md
> +  table_type    = "DLI"
seems that the usage could not run correctly, please have a check.

2021-10-28 08:46 UTC, ShiChangkuo commented on docs/resources/dli_table.md
> +* `name` - (Required, String, ForceNew)Specifies the table name. Name of a newly created resource table. The name can contain
please add a space

2021-10-28 08:46 UTC, ShiChangkuo commented on docs/resources/dli_table.md
> +* `name` - (Required, String, ForceNew)Specifies the table name. Name of a newly created resource table. The name can contain
please add a space

2021-10-28 08:46 UTC, ShiChangkuo commented on huaweicloud/services/dli/resource_huaweicloud_dli_table.go
> +						"column_name": {
suggest to rename to `name`

2021-10-28 08:46 UTC, ShiChangkuo commented on huaweicloud/services/dli/resource_huaweicloud_dli_table.go
> +	d.SetId(fmt.Sprintf("%s.%s", databaseName, tableName))
please use / to separate

2021-10-28 08:46 UTC, ShiChangkuo commented on docs/resources/dli_table.md
> +## Import
you can get an similar example from: https://registry.terraform.io/providers/huaweicloud/huaweicloud/latest/docs/resources/apig_api#import

2021-10-28 11:51 UTC, hmbig2 commented
make testacc TEST='./huaweicloud/services/acceptance/dli' TESTARGS='-run=TestAccResourceDliTable'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./huaweicloud/services/acceptance/dli -v -run=TestAccResourceDliTable -timeout 360m -parallel 4
=== RUN   TestAccResourceDliTable_basic
=== PAUSE TestAccResourceDliTable_basic
=== RUN   TestAccResourceDliTable_OBS
=== PAUSE TestAccResourceDliTable_OBS
=== CONT  TestAccResourceDliTable_basic
=== CONT  TestAccResourceDliTable_OBS
--- PASS: TestAccResourceDliTable_basic (23.82s)
--- PASS: TestAccResourceDliTable_OBS (26.24s)
PASS
ok      github.com/huaweicloud/terraform-provider-huaweicloud/huaweicloud/services/acceptance/dli       26.314s

2021-10-29 06:24 UTC, ShiChangkuo approved these changes

2021-10-29 06:25 UTC, ShiChangkuo commented
/lgtm

2021-10-29 06:29 UTC, merged