add NatGateway datasource
huaweicloud/terraform-provider-huaweicloud pull request #501
Opened 2020-08-31 01:39 UTC by Jason-Zhang9309

make testacc TEST='./huaweicloud' TESTARGS='-run TestAccNatGatewayDataSource_basic'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./huaweicloud -v -run TestAccNatGatewayDataSource_basic -timeout 360m
=== RUN   TestAccNatGatewayDataSource_basic
--- PASS: TestAccNatGatewayDataSource_basic (87.17s)
PASS
ok      github.com/huaweicloud/terraform-provider-huaweicloud/huaweicloud       87.207s

2020-08-31 07:22 UTC, niuzhenguo requested changes

2020-08-31 07:22 UTC, niuzhenguo commented on website/docs/d/nat_gateway.html.markdown
> +---
need to add `subcategory: "NAT Gateway (NAT)"`

2020-08-31 07:22 UTC, niuzhenguo commented on website/docs/d/nat_gateway.html.markdown
> +# huaweicloud\_networking\_network\_v2
huaweicloud\_nat\_gateway

2020-08-31 07:22 UTC, niuzhenguo commented on huaweicloud/data_source_huaweicloud_nat_gateway_v2_test.go
> +}
these networking resources are all deprecated, use vpc and vpc_subnet resources instead.

2020-08-31 07:22 UTC, niuzhenguo commented on huaweicloud/data_source_huaweicloud_nat_gateway_v2_test.go
> +resource "huaweicloud_nat_gateway_v2" "nat_1" {
use `huaweicloud_nat_gateway` instead

2020-08-31 07:22 UTC, niuzhenguo commented on huaweicloud/data_source_huaweicloud_nat_gateway_v2_test.go
> +	name = huaweicloud_nat_gateway_v2.nat_1.name
ditto.

2020-08-31 07:22 UTC, niuzhenguo commented on huaweicloud/data_source_huaweicloud_nat_gateway_v2_test.go
> +	id = huaweicloud_nat_gateway_v2.nat_1.id
ditto.

2020-08-31 07:22 UTC, niuzhenguo commented on huaweicloud/data_source_huaweicloud_nat_gateway_v2.go
> +			"limit": {
`limit` is unneeded. it's useless for us.

2020-08-31 07:22 UTC, niuzhenguo commented on huaweicloud/data_source_huaweicloud_nat_gateway_v2.go
> +		DeprecationMessage: "use huaweicloud_vpc_subnet_v1 data source instead",
remove this DeprecationMessage.

2020-08-31 07:22 UTC, niuzhenguo commented on huaweicloud/data_source_huaweicloud_nat_gateway_v2.go
> +			"tenant_id": {
`tenant_id` is unneeded here.

2020-08-31 07:22 UTC, niuzhenguo commented on huaweicloud/data_source_huaweicloud_nat_gateway_v2.go
> +			"region": {
`region` is unneeded.

2020-08-31 07:22 UTC, niuzhenguo commented on huaweicloud/data_source_huaweicloud_nat_gateway_v2.go
> +			"created_at": {
`createdat` is unneeded.

2020-08-31 07:22 UTC, niuzhenguo commented on huaweicloud/data_source_huaweicloud_nat_gateway_v2.go
> +	if v, ok := d.GetOk("status"); ok {
why not just passing the status argument as above.

2020-09-01 02:41 UTC, ShiChangkuo commented on website/docs/d/nat_gateway.html.markdown
> +* `id` - (Optional) The ID of the NAT gateway.
No need to add `optional` or `required` tags on attributes.

2020-09-03 01:50 UTC, niuzhenguo requested changes

2020-09-03 01:50 UTC, niuzhenguo commented on website/docs/d/nat_gateway.html.markdown
> +subcategory: "NAT Gateway (NAT)"
this should be under "---"

2020-09-03 01:50 UTC, niuzhenguo commented on website/docs/d/nat_gateway.html.markdown
> +* `id` - The ID of the NAT gateway.
Attributes can be only ones that not included in `Argument Reference`

2020-09-03 01:50 UTC, niuzhenguo commented on huaweicloud/data_source_huaweicloud_nat_gateway_v2_test.go
> +	router_id = "${huaweicloud_vpc.vpc_1.id}"
just use `router_id = huaweicloud_vpc.vpc_1.id`

2020-09-03 01:50 UTC, niuzhenguo commented on huaweicloud/data_source_huaweicloud_nat_gateway_v2_test.go
> +	name = "vpc_1"
all name should use the value of the `name` argument.

2020-09-03 01:50 UTC, niuzhenguo commented on huaweicloud/data_source_huaweicloud_nat_gateway_v2_test.go
> +	name       = "subnet_1"
ditto.

2020-09-04 06:33 UTC, niuzhenguo approved these changes

2020-09-04 06:34 UTC, merged